Added zhTW support and rough translations
RestedXP/RXPGuides pull request #52
Opened 2022-09-04 09:13 UTC by hong0311

2022-09-04 09:22 UTC, hong0311 commented on locale/zhTW.lua
> +-- Core Addon UI translations
Did some rough translations on top of the simplified chinese text. The text should is translated and corrected to be more aligned to Taiwan/Hong Kong Chinese.

2022-09-05 05:43 UTC, SabreValkyrn requested changes
Thanks for putting this together!

There's a fairly large technical limitation though that unfortunately makes bad grammar.

2022-09-05 05:43 UTC, SabreValkyrn commented on locale/zhTW.lua
> +L["I just leveled from %d to %d in %s"] =
While not grammatically correct, the string substitutions (`%s`, `%d`, `%.2f`, etc) need to be in the same order as their enUS/key with the current logic.

There's a lot more like this in this file, but sadly `string.format` requires substitutions in a specific order. Most of these changes would end up with `0` showing up for most numbers.

https://wowpedia.fandom.com/wiki/API_format

2022-09-05 07:55 UTC, hong0311 commented on locale/zhTW.lua
> +L["I just leveled from %d to %d in %s"] =
Got it. I'll take a deeper look and change the needed lines. In that case I assume that we'll sacrafice some grammatical correctness.

2022-09-05 18:44 UTC, hong0311 commented
I've updated the strings and they should now all follow the correct formatting parameter order.

2022-09-05 19:02 UTC, SabreValkyrn approved these changes

2022-09-05 19:03 UTC, merged